### ISSUE TITLE
Question about "ADSignInLogsGraph-Analyzer v0.1"

### ISSUE THREAD

**Issue by Camel0101** [evild3ad/Microsoft-Analyzer-Suite#1]
Hello,

I was wondering if “ADSignInLogsGraph-Analyzer v0.1” could also work with the json output of the “Get-ADSignInLogs” command in addition to “Get-ADSignInLogsGraph” from Microsoft-Extractor-Suite ?

Thank you !

**Comment by evild3ad** [comment]
Thanks for using the Microsoft-Analyzer-Suite.

I wrote ADSignInLogs-Analyzer before I started writing ADSignInLogsGraph-Analyzer. It is not planned to release and/or maintain it. Get-ADSignInLogsGraph uses Microsoft.Graph.Beta...it is a little bit faster and contains additional valueable properties. It is for example the only way to detect device code phishing attacks. 

I recommend to use Get-ADSignInLogsGraph in your next M365 investigations.
