### ISSUE TITLE
MFA-Analyzer User Registration Details Does Not Exist

### ISSUE THREAD

**Issue by DoubtfulTurnip** [evild3ad/Microsoft-Analyzer-Suite#3]
When running the MFA-Analyzer.ps1, the script is able to process the *-MFA-AuthenticationMethods.csv but for some reason it doesn't seem to detect the *-MFA-UserRegistrationDetails.csv file that is located in the same directory.

The error states; [Error] C:\Pathtofolder\YYYYMMDDHHMM-UserRegistrationDetails.csv does not exist.

Which is true because the CSV is named YYYYMMDDHHMM-**MFA**-UserRegistrationDetails.csv

Are you able to tell me if this is caused by something I am doing incorrectly or whether something else could be the issue?

**Comment by evild3ad** [comment]
Thanks for reporting. I fixed MFA-Analyzer.ps1 and released Microsoft-Analyzer-Suite v1.0.1.

> [!TIP]
> You find a newer version of Get-MFAStatus.ps1 already in the GitHub repo of the Microsoft-Extractor-Suite! ;-)
