### ISSUE TITLE
ASN-Blacklist.csv - Missing quote in line 10

### ISSUE THREAD

**Issue by SecurityAura** [evild3ad/Microsoft-Analyzer-Suite#4]
Sorry for opening an issue just because of that. Apparently, I need to be verified on Twitter to DM you.

I was looking at our ASN-Blacklist.csv file as I was thinking of starting one of my own, with the ASNs I encounter in my BECs to then see that you pretty much cover all of them.

When opening the file in Github, you get this error because of a missing quote on line 10 for the date.

![image](https://github.com/user-attachments/assets/4857090a-9468-4083-a8b7-9c8c3224a38a)

This being said, do you accept ASN submissions for that blacklist, or do you want to keep it yours in the sense that you'll only add ASNs you personally encountered in your BECs?

**Comment by evild3ad** [comment]
Thanks for reaching out. Feel free to DM me on Twitter. I had to follow you back. 

You find also my email address in the header of any script...what you prefer.

I added the missing quoting in line 10.

Feel free add additional ASN to this blacklist. I would appreciate it! 💪

**Comment by SecurityAura** [comment]
Awesome, thank you! :) 

In that case I'll open a PR soon for some ASNs I just encountered in my current BECs to enhance that list.

**Comment by evild3ad** [comment]
I updated the ASN-Blacklist.csv from 54 to 308 entries.
